services:
  swagfront:
    container_name: swagfront
    hostname: swagfront
    volumes:
      - <your_host_proxyconfs_folder>:/swag/proxy-confs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SWAG_PROXY_CONFS_DIR: /swag/proxy-confs
      BASE_DOMAIN: example.com
    ports:
      - '5559:5559'
